#----------------------------------------------------------------------
# This is the Corona Warn App master configuration file.
# ----------------------------------------------------------------------
#
# This configuration file will be fetched by the mobile app in order to function.
#
# For details regarding other properties - please see their respective .proto configuration files.
#
# Change this file with caution!

risk-calculation-parameters: !include risk-calculation-parameters.yaml
diagnosis-keys-data-mapping: !include diagnosis-keys-data-mapping.yaml
daily-summaries-config: !include daily-summaries-config.yaml
