---
logging:
  level:
    org:
      springframework:
        web: DEBUG
    app:
      coronawarn: DEBUG

services:
  distribution:
    signature:
      app-bundle-id: de.rki.coronawarnapp-dev
      android-package: de.rki.coronawarnapp.dev
