---
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}

services:
  distribution:
    paths:
      output: /tmp/distribution
    objectstore:
      access-key: ${CWA_OBJECTSTORE_ACCESSKEY}
      secret-key: ${CWA_OBJECTSTORE_SECRETKEY}
      endpoint: ${CWA_OBJECTSTORE_ENDPOINT}
      bucket: ${CWA_OBJECTSTORE_BUCKET}
      port: ${CWA_OBJECTSTORE_PORT}
      set-public-read-acl-on-put-object: false
