default: true

MD013: false #https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013
MD033: false #https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md033
MD034: false #https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md034
