---
spring:
  flyway:
    password: ${POSTGRESQL_PASSWORD_FLYWAY}
    user: ${POSTGRESQL_USER_FLYWAY}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST}:${POSTGRESQL_SERVICE_PORT}/${POSTGRESQL_DATABASE}?ssl=true&sslmode=verify-full&sslrootcert=${SSL_POSTGRES_CERTIFICATE_PATH}&sslcert=${SSL_EVENT_REGISTRATION_CERTIFICATE_PATH}&sslkey=${SSL_EVENT_REGISTRATION_PRIVATE_KEY_PATH}
    username: ${POSTGRESQL_USER_EVENT_REGISTRATION}
    password: ${POSTGRESQL_PASSWORD_EVENT_REGISTRATION}
