---
event-registration:
  version: 0
  privatekey: ${EVENT_REGISTRATION_SECRET}
  signature:
    # The algorithm name.
    algorithm-name: ${EVENT_REGISTRATION_SIGNATURE_ALGORITHM_NAME:sha256WithRSAEncryption}
    # The security provider.
    security-provider: BC

spring:
  main:
    web-application-type: NONE
  transaction:
    default-timeout: 20
  flyway:
    enabled: true
    locations: classpath:/eventregistration/db/migration, classpath:/eventregistration/db/specific/{vendor}
    password: ${POSTGRESQL_PASSWORD_FLYWAY:local_setup_flyway}
    user: ${POSTGRESQL_USER_FLYWAY:local_setup_flyway}
    schemas: event_registration
  # Postgres configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_SERVICE_HOST:localhost}:${POSTGRESQL_SERVICE_PORT:5432}/${POSTGRESQL_DATABASE:cwa_event_registration}
    username: ${POSTGRESQL_USER_EVENT_REGISTRATION:local_setup_event_registration}
    password: ${POSTGRESQL_PASSWORD_EVENT_REGISTRATION:local_setup_event_registration}
    hikari:
      schema: event_registration

logging:
  level:
    org:
      springframework:
        web: INFO
    app:
      coronawarn: INFO
    com:
      netflix:
        config:
          sources:
            URLConfigurationSource: ERROR
