name: hadolint-analysis-workflow

on:
    pull_request:
        branches:
        - main
        - release/**
        paths:
        - '**/Dockerfile'

jobs:
    hadolint-callback:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Pull HaDoLint image
            run: docker pull hadolint/hadolint
        -   name: Lint Dockerfile
            run: docker run --rm --interactive hadolint/hadolint < ./services/callback/Dockerfile
    hadolint-distribution:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Pull HaDoLint Image
            run: docker pull hadolint/hadolint
        -   name: Lint Dockerfile
            run: docker run --rm --interactive hadolint/hadolint < ./services/distribution/Dockerfile
    hadolint-download:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Pull HaDoLint Image
            run: docker pull hadolint/hadolint
        -   name: Lint Dockerfile
            run: docker run --rm --interactive hadolint/hadolint < ./services/download/Dockerfile
    hadolint-submission:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Pull HaDoLint Image
            run: docker pull hadolint/hadolint
        -   name: Lint Dockerfile
            run: docker run --rm --interactive hadolint/hadolint < ./services/submission/Dockerfile
    hadolint-upload:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v2
        -   name: Pull HaDoLint Image
            run: docker pull hadolint/hadolint
        -   name: Lint Dockerfile
            run: docker run --rm --interactive hadolint/hadolint < ./services/upload/Dockerfile