name: maven-build

on:
    push:
        branches:
        - main
        - release/**
    pull_request:
        branches:
        - main
        - release/**

permissions:
    statuses: write
    checks: write
    pull-requests: write

jobs:
    mvn-verify:
        name: run mvn verify and do SonarCloud scan
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v3
        -   name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: temurin
                cache: maven
        -   name: mvn verify
            run: mvn -B -P integration-test verify --fail-fast --file pom.xml -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
        -   name: SonarCloud scan
            run: mvn -B sonar:sonar --fail-never -Dorg.slf4j.simpleLogger.defaultLogLevel=warn
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        -   name: Report JUnit results at checks
            uses: dorny/test-reporter@v1
            if: always()
            with:
                name: Maven Tests
                path: '**/surefire-reports/*.xml'
                reporter: java-junit
                fail-on-error: true
                list-suites: 'failed'
                list-tests: 'failed'
        -   name: Report JUnit results at checks as comment
            uses: EnricoMi/publish-unit-test-result-action/composite@v1
            if: always()
            with:
                files: '**/surefire-reports/*.xml'