name: maven-build

on:
    push:
        branches:
        - main
        - release/**
    pull_request:
        branches:
        - main
        - release/**

jobs:
    mvn-verify:
        name: run mvn verify and do SonarCloud scan
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout repository
            uses: actions/checkout@v3
        -   name: Set up JDK 11
            uses: actions/setup-java@v3
            with:
                java-version: '11'
                distribution: temurin
                cache: maven
        -   name: mvn verify
            run: mvn -B -P integration-test verify --fail-fast --file pom.xml
        -   name: SonarCloud Scan
            uses: SonarSource/sonarcloud-github-action@v1.6
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            with:
                args: -Dsonar.organization=corona-warn-app -Dsonar.projectKey=corona-warn-app_cwa-server